config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#rails home'
  get 'about', to:'pages#about'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  item_nums = Array[2,3,4]
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello
        render html:'Hello World!'
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    include Pagy::Backend

    def index
        
        if !params[:per_page].present?
            params[:per_page] = 2 #default
        end
        
        @pagy, @categories = pagy(Category, items: params[:per_page])   
    end

    def show
        @category = Category.find(params[:id])
    end

    def new
    end

    def edit
        @category = Category.find(params[:id])
    end

    def create
        @category = Category.new(params.require(:category).permit(:name, :description, :active))
        @category.save
        redirect_to category_path(@category)
    end

    def update
        @category = Category.find(params[:id])
        @category.update(params.require(:category).permit(:name, :description, :active))
        redirect_to category_path(@category)
    end

    def destroy
        byebug
        @category = Category.find(params[:id])
        @category.update_column(:active, 0)
        redirect_to category_path(@category)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
    include Pagy::Frontend
    
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/categories/_pagination.html.erb
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @posts, :container => false %>
  </div>

app/views/categories/edit.html.erb
<h1>Edit a category</h1>
<%= form_with(model: @category ,local: true)  do |f| %>
<p>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />
</p>
<p>
  <%= f.label :description %>:
  <%= f.text_area :description %><br />
</p>
<p>
  <%= f.label :status %>:
  <%= f.check_box :active %><br />
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/categories/index.html.erb
<h1>This is categories index page</h1>

<%= pagy_nav(@pagy).html_safe %>
<%= pagy_items_selector_js(@pagy,1) %>

<label>Showing <%=@pagy.from %> to <%=@pagy.to %> from <%= @pagy.count %></label> <br/>

<%= form_tag categories_path, method: :get do %>
  <label>Show</label>
  <%= select_tag :per_page, options_for_select([2, 3, 4, 5], params[:per_page]),
   onchange: "this.form.submit();" %>
  
<% end %>
<table>
<thead>
<tr>
<td>Name</td>
<td>Description</td>
<td>Status</td>
<td>Actions</td>
</tr>
</thead>
<tbody>
<% @categories.each do |category| %>
<tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= category.active %></td>
    <td><%= link_to "Inactivate", category_path(category), method: :delete %> </td>
    <td><%= link_to "Show", category_path(category)%> </td>
    <td><%= link_to "Edit", edit_category_path(category)%> </td>
    </tr>
    <% end %>
</tbody>
<table>
<p><%= link_to "Create new category", new_category_path %></p>

app/views/categories/new.html.erb
<h1>Create new category</h1>
<%= form_with scope: :category, url:categories_path,local: true do |f| %>
<p>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />
</p>
<p>
  <%= f.label :description %>:
  <%= f.text_area :description %><br />
</p>
<p>
  <%= f.label :status %>:
  <%= f.check_box :active %><br />
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/categories/show.html.erb
<h1>Show Category</h1>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
   <strong>Description:</strong>
   <%= @category.description %>
</p>
<p>
   <strong>Status:</strong>
   <%= @category.active %>
</p>
<p><td><%= link_to "Back", categories_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoftwareReviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is About Page</h1>

app/views/pages/home.html.erb
<h1>This is Home Page</h1>